import Head from 'next/head';
import { useEffect, useState } from 'react';
import MapViewer from '../components/MapViewer';

export default function Home() {
  const [text, setText] = useState('');

  useEffect(() => {
    fetch('/api')
      .then((res) => res.json())
      .then((value) => setText(value.text))
      .catch((reason) => console.log(reason));
  }, []);

  return (
    <>
      <Head>
        <title>IGC Viewer</title>
        <meta
          name='description'
          content='Web map application for viewing .igc files generated by glider flight trackers'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex h-screen flex-col'>
        <header>
          <nav className='bg-gray-800 px-2 text-white sm:px-4 lg:px-8'>
            <div className='flex h-20 items-center justify-between'>
              <div className='flex items-center gap-8'>
                <span className='h-12 w-12 bg-indigo-700'></span>
                <span className='text-3xl font-bold tracking-wider'>IGC Viewer</span>
              </div>
              <div>Buttons: {text}</div>
            </div>
          </nav>
        </header>
        <main className='flex overflow-hidden bg-gray-50'>
          <div className='scrollbar-hidden flex w-96 flex-shrink-0 flex-col overflow-y-auto bg-gray-700'>
            <div>
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((value) => (
                <div key={value} className='flex h-36 items-center justify-center border-b border-gray-800'>
                  {' '}
                  <div className='text-white'>{value}</div>
                </div>
              ))}
            </div>
          </div>
          <MapViewer />
        </main>
      </div>
    </>
  );
}
